# Generated by Django 2.2.6 on 2019-10-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('priority', models.IntegerField()),
                ('parent_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list_app.Todo')),
            ],
        ),
    ]
