# Generated by Django 2.2.6 on 2019-10-25 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0003_auto_20191025_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 7, 43, 39, 958658, tzinfo=utc), verbose_name='date published'),
        ),
    ]
